name: pihole

networks:
  infra:
    external: true

services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    env_file:
      - ./config/pihole.secrets.env
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      TZ: 'Europe/Stockholm'
      FTLCONF_REPLY_ADDR4: "$LAB_IP"
      # FTLCONF_dns_listeningMode: 'ALL'
      # DNSMASQ_LISTENING: 'all'
    volumes:
      - './data/etc-pihole:/etc/pihole'
      - './data/etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - SYS_NICE
    networks:
      - infra
